### ISSUE TITLE
[FEAT] Setup analytics (visits and views)

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/process-analytics.dev#3]
if we use google analytics, see https://www.gatsbyjs.com/docs/recipes/deploying-your-site/#setting-up-google-analytics

**Comment by csouchet** [comment]
I think it's better to user Google analytics in a first step, because it's integrated with Gatsby.
If we choose to use it, we need to create a google account for the organisation : https://support.google.com/analytics/answer/1008015?hl=en

https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-analytics/
